version: '3.8'

services:
  app:
    build:
      context: ./pokemon-app
    ports:
      - "3000:3000"
    networks:
      - app-network
    env_file:
      - .env
    environment:
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE: ${DB_DATABASE}
      CACHE_TYPE: ${CACHE_TYPE}
      CACHE_HOST: ${CACHE_HOST}
      CACHE_PORT: ${CACHE_PORT}
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    container_name: postgres-db
    ports:
      - "5432:5432"
    networks:
      - app-network
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    env_file:
      - .env
    environment:
      REDIS_HOST: ${CACHE_HOST}
      REDIS_PORT: ${CACHE_PORT}

networks:
  app-network:
    driver: bridge
